// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {search} from '../models';
import {types} from '../models';

export function CancelStream():Promise<void>;

export function DeleteAPIKey():Promise<void>;

export function GetAvailableModels():Promise<Array<string>>;

export function GetConfig():Promise<config.Config>;

export function GetFileTree():Promise<types.FileNode>;

export function GetRootPath():Promise<string>;

export function GetTheme():Promise<string>;

export function GetVertexRegions():Promise<Array<string>>;

export function HasAPIKey():Promise<boolean>;

export function OpenFolder():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetCornerRadius(arg1:number):Promise<void>;

export function SetRootPath(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartPipe(arg1:string):Promise<string>;

export function StartStream(arg1:string):Promise<void>;

export function StopPipe():Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function SaveUISettings(arg1:main.UISettings):Promise<void>;

export function SearchFiles(arg1:string):Promise<Array<search.SearchResult>>;

export function GetHighlights(arg1:string):Promise<Array<highlights.Highlight>>;

export function AddHighlight(arg1:highlights.Highlight):Promise<void>;

export function RemoveHighlight(arg1:string,arg2:string):Promise<void>;

export function ClearHighlights(arg1:string):Promise<void>;

export function GetInitialFile():Promise<string>;
