// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileTree(): Promise<any>;
export function ReadFile(arg1: string): Promise<string>;
export function GetRootPath(): Promise<string>;
export function OpenFolder(): Promise<string>;
export function SetRootPath(arg1: string): Promise<void>;
export function GetConfig(): Promise<any>;
export function UpdateConfig(arg1: any): Promise<void>;
export function GetTheme(): Promise<string>;
export function SetTheme(arg1: string): Promise<void>;
