// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {types} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetFileTree():Promise<types.FileNode>;

export function GetRootPath():Promise<string>;

export function GetTheme():Promise<string>;

export function OpenFolder():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SetRootPath(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function UpdateConfig(arg1:config.Config):Promise<void>;
