// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream() {
  return window['go']['main']['App']['CancelStream']();
}

export function DeleteAPIKey() {
  return window['go']['main']['App']['DeleteAPIKey']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFileTree() {
  return window['go']['main']['App']['GetFileTree']();
}

export function GetRootPath() {
  return window['go']['main']['App']['GetRootPath']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetVertexRegions() {
  return window['go']['main']['App']['GetVertexRegions']();
}

export function HasAPIKey() {
  return window['go']['main']['App']['HasAPIKey']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetCornerRadius(arg1) {
  return window['go']['main']['App']['SetCornerRadius'](arg1);
}

export function SetRootPath(arg1) {
  return window['go']['main']['App']['SetRootPath'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartPipe(arg1) {
  return window['go']['main']['App']['StartPipe'](arg1);
}

export function StartStream(arg1) {
  return window['go']['main']['App']['StartStream'](arg1);
}

export function StopPipe() {
  return window['go']['main']['App']['StopPipe']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function SaveUISettings(arg1) {
  return window['go']['main']['App']['SaveUISettings'](arg1);
}

export function SearchFiles(arg1) {
  return window['go']['main']['App']['SearchFiles'](arg1);
}

export function GetHighlights(arg1) {
  return window['go']['main']['App']['GetHighlights'](arg1);
}

export function AddHighlight(arg1) {
  return window['go']['main']['App']['AddHighlight'](arg1);
}

export function RemoveHighlight(arg1, arg2) {
  return window['go']['main']['App']['RemoveHighlight'](arg1, arg2);
}

export function ClearHighlights(arg1) {
  return window['go']['main']['App']['ClearHighlights'](arg1);
}

export function GetInitialFile() {
  return window['go']['main']['App']['GetInitialFile']();
}

export function TranslateText(arg1, arg2) {
  return window['go']['main']['App']['TranslateText'](arg1, arg2);
}
