// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH A MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileTree() {
    return window['go']['main']['App']['GetFileTree']();
}

export function ReadFile(arg1) {
    return window['go']['main']['App']['ReadFile'](arg1);
}

export function GetRootPath() {
    return window['go']['main']['App']['GetRootPath']();
}

export function OpenFolder() {
    return window['go']['main']['App']['OpenFolder']();
}

export function SetRootPath(arg1) {
    return window['go']['main']['App']['SetRootPath'](arg1);
}

export function GetConfig() {
    return window['go']['main']['App']['GetConfig']();
}

export function UpdateConfig(arg1) {
    return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function GetTheme() {
    return window['go']['main']['App']['GetTheme']();
}

export function SetTheme(arg1) {
    return window['go']['main']['App']['SetTheme'](arg1);
}
